# 首先创建一个 ExternalName 类型的 Service
apiVersion: v1
kind: Service
metadata:
  name: unit-test-writer
  namespace: default
spec:
  type: ExternalName
  externalName: localhost # 访问本地服务
  ports:
    - port: 80
      targetPort: 8088
      protocol: TCP
---
# 然后创建 Ingress 规则
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unit-test-writer
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / # 如果使用 nginx ingress controller
spec:
  ingressClassName: nginx # 指定 ingress controller
  rules:
    - host: test.sxwl.ai # 替换为您想要使用的域名
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unit-test-writer # 对应上面创建的 Service 名称
                port:
                  number: 80
